version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - tz-chat

  app:
    container_name: app
    build:
      context: ./docker
      dockerfile: Dockerfile
    working_dir: '/var/www'
    volumes:
      - './src:/var/www'
      - './docker/supervisor/supervisord.conf:/etc/supervisord.conf'
      - './docker/supervisor/horizon.conf:/etc/supervisor/conf.d/horizon.conf'
    user: docker
    command: ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]
    ports:
      - "3001:80"
      - "5173:5173"
      - "6001:6001"
    depends_on:
      - mysql
      - redis
    networks:
      - tz-chat

  pma:
    container_name: pma
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - tz-chat

  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE=tz-chat
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - tz-chat

  redis:
    container_name: redis
    image: redis:alpine
    hostname: redis
    restart: always
    command: "redis-server --appendonly yes --replica-read-only no"
    ports:
      - "6379:6379"
    networks:
      - tz-chat

  mailcatcher:
    container_name: mailcatcher
    restart: on-failure:10
    image: dockage/mailcatcher:0.7.1
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - tz-chat

networks:
  tz-chat:
    driver: bridge
